### ISSUE TITLE
All things to still be done before we can call it a day

### ISSUE THREAD

**Issue by jasperhartong** [jasperhartong/gatsby-starter-netlify-cms#1]
# TODO

* [ ] Ensure preview image has correct size so highlights have correct shape
* [ ] Add enums to the data model
* [ ] Clean up data model (consistent handling of titles and descriptions)
* [ ] Clean up EVERYTHING :) Remove pages, api endpoint
* [ ] Create 1 REAL procedure, with REAL data: see if data model is correct
* [ ] Style it
* [ ] Add a pane for highlight details
* [ ] Test offline possibilities
* [ ] Create Step component, minimze tree in procedure.js
* [ ] Add better styled home view, just use a list instead of cards..
* [ ] Update all meta data of the site
* [ ] Mobile view tags
* [ ] Rename repo (gasp)

**Comment by jasperhartong** [comment]
And much more
